package:
  name: babyfood
  version: {{ environ.get('GIT_DESCRIBE_TAG', "0.0.0") }}

source:
  path: .

build:
  # The build number should be incremented for new builds of the same version
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: "testing"
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python
#    - units
#    - pycairo

test:
  requires:
    - nose
  imports:
    - babyfood
  commands:
    - python -m babyfood.testing 

about:
  home: https://github.com/meawoppl/babyfood
  license: BSD
  summary: tool to make PCBs
